valor1= input("Dime una palabra:")
valor2= input("Dime otra palabra:")
valor3= input("Dime la tercera palabra:")
valor4= input("Dime la cuarta palabra:")
valor5= input("Dime la ultima palabra:")
print(valor1,valor2,valor3,valor4,valor5)
print(valor1,",",valor2,",",valor3,",",valor4,",",valor5)
